---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: deploy-vm-summit-rh-job
  namespace: aap
spec:
  connection_secret: aapaccess
  job_template_name: create-apache-vm
  extra_vars: {
"vm_name": "rh-summit-vm"
}
